# Generated by Django 5.2.7 on 2025-11-04 12:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("current_queue_number", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialization", models.CharField(max_length=100)),
                ("room_number", models.CharField(blank=True, max_length=10, null=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("medical_history", models.TextField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=10,
                    ),
                ),
                ("symptoms", models.TextField(blank=True, null=True)),
                (
                    "registered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queues",
                        to="queue_app.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queues",
                        to="queue_app.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateTimeField(auto_now_add=True)),
                ("symptoms", models.TextField(blank=True)),
                ("diagnosis", models.TextField(blank=True)),
                ("treatment", models.TextField(blank=True)),
                ("medications_prescribed", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("next_visit_date", models.DateField(blank=True, null=True)),
                ("ai_diagnosis_confidence", models.FloatField(blank=True, null=True)),
                ("treatment_effectiveness", models.FloatField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="queue_app.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="queue_app.patient",
                    ),
                ),
            ],
            options={
                "db_table": "medical_records",
                "ordering": ["-visit_date"],
                "indexes": [
                    models.Index(
                        fields=["patient", "visit_date"],
                        name="medical_rec_patient_ec477f_idx",
                    ),
                    models.Index(
                        fields=["visit_date"], name="medical_rec_visit_d_9bd080_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QueueTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_consultation", "In Consultation"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.DateTimeField(auto_now_add=True)),
                (
                    "consultation_start_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("consultation_end_time", models.DateTimeField(blank=True, null=True)),
                ("estimated_wait_time", models.IntegerField(blank=True, null=True)),
                ("ai_priority_score", models.FloatField(default=0.5)),
                (
                    "predicted_consultation_time",
                    models.IntegerField(blank=True, null=True),
                ),
                ("symptom_analysis", models.JSONField(blank=True, null=True)),
                (
                    "ai_suggested_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_suggestions",
                        to="queue_app.doctor",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="queue_app.department",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="queue_app.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="queue_app.patient",
                    ),
                ),
            ],
            options={
                "db_table": "queue_tickets",
                "ordering": ["check_in_time"],
                "indexes": [
                    models.Index(
                        fields=["status", "department"],
                        name="queue_ticke_status_99e68e_idx",
                    ),
                    models.Index(
                        fields=["check_in_time"], name="queue_ticke_check_i_f403dd_idx"
                    ),
                    models.Index(
                        fields=["patient", "status"],
                        name="queue_ticke_patient_e793c7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VirtualCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "virtual_card_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, unique=True
                    ),
                ),
                ("has_physical_card", models.BooleanField(default=False)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("health_risk_score", models.FloatField(blank=True, null=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_card",
                        to="queue_app.patient",
                    ),
                ),
            ],
            options={
                "db_table": "virtual_cards",
                "indexes": [
                    models.Index(
                        fields=["virtual_card_id"],
                        name="virtual_car_virtual_378552_idx",
                    )
                ],
            },
        ),
    ]
